server:
  host: 0.0.0.0
  port: 8080

database:
  host: 113.44.1.253
  port: 3306
  user: root
  password: root
  dbname: chat
  charset: utf8mb4

jwt:
  secret: your-secret-key-change-this
  expires_in: 24 

deepseek:
  api_key: sk-ab05874f5a4847bfa44c0a8c07db03e6
  base_url: https://api.deepseek.com/v1
  model: deepseek-chat 
  reasoner_model: deepseek-reasoner 