version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root    # root用户密码
      MYSQL_DATABASE: chat                  # 自动创建的数据库名
      MYSQL_USER: seeyu                      # 创建的普通用户名
      MYSQL_PASSWORD: seeyu              # 普通用户密码
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d  # 初始化SQL脚本目录
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge